<?php

/**
 * @file
 * Contains sponsor.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sponsor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sponsor module.
    case 'help.page.sponsor':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Sponsor') . '</p>';
      return $output;

    default:
  }
}
